# Generated by Django 5.0 on 2023-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
